### ISSUE TITLE
Create Rstudio Project for your repository

### ISSUE THREAD

**Issue by dshizuka** [lexiefoster/BIOS967_Foster#2]
You should create a Rstudio Project for your independent project repository. Do this by opening RStudio, Clicking on New Project > Existing Directory, and then selecting the local version of your repository. Then push the changes to GitHub.

**Comment by lexiefoster** [comment]
I believe I created an Rstudio Project for my independent project repository but am having trouble with the push and pull steps. I keep getting this error message (see attached screenshot) when I try to pull. Not sure if I am missing a step... 

<img width="1680" alt="Screenshot 2023-10-06 at 3 01 14 PM" src="https://github.com/lexiefoster/BIOS967_Foster/assets/142915950/6fdbdf7a-c978-4352-bc1b-120eea0af7cc">

**Comment by dshizuka** [comment]
Hey Lexie,

Try doing the push and pull through GitHub Desktop instead of Rstudio. It seems to work much better. Let me know if that works or not.

From: Lexie Foster ***@***.***>
Date: Friday, October 6, 2023 at 3:01 PM
To: lexiefoster/BIOS967_Foster ***@***.***>
Cc: Dai Shizuka ***@***.***>, Author ***@***.***>
Subject: Re: [lexiefoster/BIOS967_Foster] Create Rstudio Project for your repository (Issue #2)
Non-NU Email
________________________________

I believe I created an Rstudio Project for my independent project repository but am having trouble with the push and pull steps. I keep getting this error message (see attached screenshot) when I try to pull. Not sure if I am missing a step...
[Screenshot 2023-10-06 at 3 01 14 PM]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/142915950/273320538-6fdbdf7a-c978-4352-bc1b-120eea0af7cc.png__;!!PvXuogZ4sRB2p-tU!FzC_VVwT1he2BV9YbSH5P38fjCJGjPirdMjjrJNfAfYPEZOOuD22_y-2qDSZNwY36jWLvpQ-e98QfZ3-Cx3BgEAX2A$>

**Comment by lexiefoster** [comment]
I added my repository BIOS967_Foster to GitHub Desktop (first screenshot) and when trying to "pull origin", I get this error message (second screenshot). Hmmm I'm wondering if somewhere along the line, I missed a step that would cause pulling and pushing to run into an issue? I appreciate all of your help with this! 
<img width="1680" alt="Screenshot 2023-10-06 at 3 23 19 PM" src="https://github.com/lexiefoster/BIOS967_Foster/assets/142915950/3ab7af43-a7c4-4d99-953c-746c641d11b0">
<img width="1680" alt="Screenshot 2023-10-06 at 3 23 31 PM" src="https://github.com/lexiefoster/BIOS967_Foster/assets/142915950/cafe78c4-3170-4689-aeac-ed75a0bed4dd">

**Comment by dshizuka** [comment]
﻿Hey Lexie,
I think there might be a conflict with the folder you created called “Data” vs. a folder I already created and pushed, called “data” (I apologize, I shouldn’t have done that).
I’ve deleted the folder I had created. Try to pull again now. If that works, it should allow you to push your new folder.

Dai

From: Lexie Foster ***@***.***>
Date: Friday, October 6, 2023 at 3:26 PM
To: lexiefoster/BIOS967_Foster ***@***.***>
Cc: Dai Shizuka ***@***.***>, Author ***@***.***>
Subject: Re: [lexiefoster/BIOS967_Foster] Create Rstudio Project for your repository (Issue #2)
Non-NU Email
________________________________

I added my repository BIOS967_Foster to GitHub Desktop (first screenshot) and when trying to "pull origin", I get this error message (second screenshot). Hmmm I'm wondering if somewhere along the line, I missed a step that would cause pulling and pushing to run into an issue? I appreciate all of your help with this!
[Screenshot 2023-10-06 at 3 23 19 PM]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/142915950/273324486-3ab7af43-a7c4-4d99-953c-746c641d11b0.png__;!!PvXuogZ4sRB2p-tU!Em4L8NGASAL22HSntrh5sTMaLkib2XhoNqS2ggypEVFHSRS0NNGZrfb8wralWiaUFo9yNEBl0QcMTXLNf33J3eCixg$>
[Screenshot 2023-10-06 at 3 23 31 PM]<https://urldefense.com/v3/__https:/user-images.githubusercontent.com/142915950/273324522-cafe78c4-3170-4689-aeac-ed75a0bed4dd.png__;!!PvXuogZ4sRB2p-tU!Em4L8NGASAL22HSntrh5sTMaLkib2XhoNqS2ggypEVFHSRS0NNGZrfb8wralWiaUFo9yNEBl0QcMTXLNf33rYkV7Rw$>

**Comment by lexiefoster** [comment]
Sweet, I believe that worked, thanks!

**Comment by dshizuka** [comment]
[like]  Dai Shizuka reacted to your message:
________________________________
